services:
  mokakbob-api:
    build:
      context: .
      args:
        MODULE_NAME: mokakbob-api
    container_name: mokakbob-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SERVER_PORT=8080
    restart: always
    networks:
      - monitoring-network

  mokakbob-consumer:
    build:
      context: .
      args:
        MODULE_NAME: mokakbob-consumer
    container_name: mokakbob-consumer
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SERVER_PORT=8081
    restart: always
    networks:
      - monitoring-network

  mokakbob-batch:
    build:
      context: .
      args:
        MODULE_NAME: mokakbob-batch
    container_name: mokakbob-batch
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SERVER_PORT=8082
    restart: always
    networks:
      - monitoring-network

networks:
  monitoring-network:
    external: true
