spring:
  profiles:
    active: local   # 기본 실행 환경(local), 배포 시 prod로 변경

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: read:user,user:email
            client-name: GitHub
        provider:
          github:
            user-name-attribute: id

jwt:
  access:
    expiration-period: 3600000     # 1시간
  refresh:
    expiration-period: 604800000   # 7일

cloud:
  aws:
    s3:
      bucket: SSS
    region:
      static: ap-northeast-2

# Prometheus + Actuator 설정 추가
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus  # prometheus endpoint 노출
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: mokakbob  # 서비스 식별용 태그
  prometheus:
    metrics:
      export:
        enabled: true
